package utils.contants;

public interface USER_PERMISSIONS {
    String READ_SELF = "READ_SELF";
    String CREATE_SELF = "CREATE_SELF";
    String UPDATE_SELF = "UPDATE_SELF";
    String DELETE_SELF = "DELETE_SELF";

    String READ_USER = "READ_USER";
    String READ_USERS = "READ_USERS";
    String CREATE_USER = "CREATE_USER";
    String UPDATE_USER = "UPDATE_USER";
    String DELETE_USER = "DELETE_USER";

    String READ_TRAIN = "READ_TRAIN";
    String READ_TRAINS = "READ_TRAINS";
    String CREATE_TRAIN = "CREATE_TRAIN";
    String UPDATE_TRAIN = "UPDATE_TRAIN";
    String DELETE_TRAIN = "DELETE_TRAIN";

    String READ_SCHEDULE = "READ_SCHEDULE";
    String READ_SCHEDULES = "READ_SCHEDULES";
    String CREATE_SCHEDULE = "CREATE_SCHEDULE";
    String UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
    String DELETE_SCHEDULE = "DELETE_SCHEDULE";

    String READ_CARRIAGE = "READ_CARRIAGE";
    String READ_CARRIAGES = "READ_CARRIAGES";
    String CREATE_CARRIAGE = "CREATE_CARRIAGE";
    String UPDATE_CARRIAGE = "UPDATE_CARRIAGE";
    String DELETE_CARRIAGE = "DELETE_CARRIAGE";

    String READ_ORDER = "READ_ORDER";
    String READ_ORDERS = "READ_ORDERS";
    String CREATE_ORDER = "CREATE_ORDER";
    String UPDATE_ORDER = "UPDATE_ORDER";
    String DELETE_ORDER = "DELETE_ORDER";

    String UNKNOWN = "UNKNOWN";
}
