version: "3.7"
services:
  app:
    build: ./
    restart: unless-stopped
    environment:
      ENV: 'PROD'
    ports:
      - "8090:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0.31
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=pbl5
      - MYSQL_ROOT_PASSWORD=040303
    volumes:
      - ./static/init.sql:/tmp/init.sql
    #       - mysql-data:/var/lib/mysql
    command: mysqld --init-file="/tmp/init.sql"
volumes:
  mysql-data:
